// web/src/pages/CharacterList.tsx
import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { listCharacters, createCharacter, deleteCharacter } from '../lib/api';
import { IconPlus, IconSword, IconShield, IconTrash, IconChevronRight } from '../components/Icon';

const CLASS_COLORS: Record<string, string> = {
    Barbarian: '#c0392b', Bard: '#8e44ad', Cleric: '#f39c12', Druid: '#27ae60',
    Fighter: '#7f8c8d', Monk: '#16a085', Paladin: '#f1c40f', Ranger: '#2ecc71',
    Rogue: '#2c3e50', Sorcerer: '#e74c3c', Warlock: '#6c3483', Wizard: '#2980b9',
};

const fieldLabel = "text-[11px] font-medium text-ash-light uppercase tracking-wide";
const field = "flex flex-col gap-1.5";

export function CharacterList() {
    const [chars, setChars] = useState<any[]>([]);
    const [loading, setLoading] = useState(true);
    const [showCreate, setShowCreate] = useState(false);
    const navigate = useNavigate();

    useEffect(() => { listCharacters().then(setChars).finally(() => setLoading(false)); }, []);

    const handleDelete = async (id: string, e: React.MouseEvent) => {
        e.stopPropagation();
        if (!confirm('Delete this character permanently?')) return;
        await deleteCharacter(id);
        setChars(c => c.filter(ch => ch.id !== id));
    };

    if (loading) return <div className="flex items-center justify-center h-[200px] text-ash">Loading characters…</div>;

    return (
        <div className="p-8 max-w-[1100px] mx-auto">
            <div className="flex items-start justify-between mb-8">
                <div>
                    <h1 className="font-display text-[28px] font-bold text-parchment">Your Characters</h1>
                    <p className="text-sm text-ash mt-1">{chars.length} adventurer{chars.length !== 1 ? 's' : ''} in your party</p>
                </div>
                <button className="flex items-center gap-2 bg-crimson border-none text-parchment px-[18px] py-2.5 rounded-md font-display text-[13px] font-semibold tracking-wide transition-colors duration-180 hover:bg-crimson-light" onClick={() => setShowCreate(true)}>
                    <IconPlus size={16} /> New Character
                </button>
            </div>

            {chars.length === 0 ? (
                <div className="text-center py-20 px-5 text-ash">
                    <IconSword size={48} className="mx-auto mb-4 opacity-30 block" />
                    <p>No characters yet. Create your first adventurer.</p>
                </div>
            ) : (
                <div className="grid grid-cols-[repeat(auto-fill,minmax(320px,1fr))] gap-4">
                    {chars.map(char => (
                        <div key={char.id} className="flex items-stretch bg-stone border border-stone-border rounded-lg cursor-pointer overflow-hidden transition-[border-color,transform] duration-180 hover:border-gold-dim hover:-translate-y-0.5" onClick={() => navigate(`/characters/${char.id}`)}>
                            <div className="w-1 shrink-0" style={{ background: CLASS_COLORS[char.class] || '#8b1a1a' }} />
                            <div className="flex-1 p-4">
                                <div className="flex items-start justify-between mb-3">
                                    <div>
                                        <h2 className="font-display text-[17px] font-semibold text-parchment">{char.name}</h2>
                                        <p className="text-xs text-ash mt-0.5">Level {char.level} {char.race} {char.class}</p>
                                    </div>
                                    <button className="bg-transparent border-none text-stone-border p-1 rounded-sm transition-colors duration-180 shrink-0 hover:text-crimson-light" onClick={e => handleDelete(char.id, e)}>
                                        <IconTrash size={14} />
                                    </button>
                                </div>
                                <div className="flex gap-3 items-center flex-wrap">
                                    <span className="flex items-center gap-1 text-xs text-ash-light"><IconShield size={12} /> {char.armor_class} AC</span>
                                    <span className="flex items-center gap-1 text-xs text-ash-light">❤ {char.current_hp}/{char.max_hp}</span>
                                    {char.is_npc && <span className="bg-gold/15 text-gold border border-gold/30 px-1.5 py-0.5 rounded text-[10px] font-semibold tracking-widest">NPC</span>}
                                </div>
                            </div>
                            <IconChevronRight size={16} className="text-stone-border self-center mr-3 shrink-0" />
                        </div>
                    ))}
                </div>
            )}

            {showCreate && (
                <CreateCharacterModal
                    onClose={() => setShowCreate(false)}
                    onCreated={c => { setChars(ch => [...ch, c]); setShowCreate(false); navigate(`/characters/${c.id}`); }}
                />
            )}
        </div>
    );
}

function CreateCharacterModal({ onClose, onCreated }: { onClose: () => void; onCreated: (c: any) => void }) {
    const RACES = ['Human', 'Elf', 'Dwarf', 'Halfling', 'Gnome', 'Half-Elf', 'Half-Orc', 'Tiefling', 'Dragonborn', 'Aasimar', 'Tabaxi', 'Kenku', 'Firbolg'];
    const CLASSES = ['Barbarian', 'Bard', 'Cleric', 'Druid', 'Fighter', 'Monk', 'Paladin', 'Ranger', 'Rogue', 'Sorcerer', 'Warlock', 'Wizard', 'Artificer'];
    const ALIGNMENTS = ['Lawful Good', 'Neutral Good', 'Chaotic Good', 'Lawful Neutral', 'True Neutral', 'Chaotic Neutral', 'Lawful Evil', 'Neutral Evil', 'Chaotic Evil'];

    const [form, setForm] = useState({
        name: '', race: 'Human', class: 'Fighter', level: 1, background: '', alignment: 'True Neutral',
        strength: 10, dexterity: 10, constitution: 10, intelligence: 10, wisdom: 10, charisma: 10,
        max_hp: 10, current_hp: 10, armor_class: 10, speed: 30, hit_dice_type: 8, hit_dice_remaining: 1,
        spellcasting_ability: 'none', is_npc: false,
    });
    const [error, setError] = useState('');

    const set = (k: string) => (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) =>
        setForm(f => ({ ...f, [k]: e.target.type === 'number' ? Number(e.target.value) : e.target.type === 'checkbox' ? (e.target as HTMLInputElement).checked : e.target.value }));

    const submit = async (e: React.FormEvent) => {
        e.preventDefault();
        try { onCreated(await createCharacter(form)); }
        catch (err: any) { setError(err?.data?.error || 'Failed to create character'); }
    };

    return (
        <div className="fixed inset-0 bg-black/75 z-[100] flex items-center justify-center p-5" onClick={onClose}>
            <div className="bg-stone border border-stone-border rounded-lg p-8 w-full max-w-[560px] max-h-[90vh] overflow-y-auto" onClick={e => e.stopPropagation()}>
                <h2 className="font-display text-xl font-bold text-parchment mb-6">Create Character</h2>
                <form onSubmit={submit} className="flex flex-col gap-4">
                    <div className="grid grid-cols-2 gap-3">
                        <div className={field}><label className={fieldLabel}>Name *</label><input value={form.name} onChange={set('name')} required placeholder="Character name" /></div>
                        <div className={field}><label className={fieldLabel}>Level</label><input type="number" min={1} max={20} value={form.level} onChange={set('level')} /></div>
                    </div>
                    <div className="grid grid-cols-2 gap-3">
                        <div className={field}><label className={fieldLabel}>Race</label><select value={form.race} onChange={set('race')}>{RACES.map(r => <option key={r}>{r}</option>)}</select></div>
                        <div className={field}><label className={fieldLabel}>Class</label><select value={form.class} onChange={set('class')}>{CLASSES.map(c => <option key={c}>{c}</option>)}</select></div>
                    </div>
                    <div className="grid grid-cols-2 gap-3">
                        <div className={field}><label className={fieldLabel}>Background</label><input value={form.background} onChange={set('background')} placeholder="Soldier, Sage…" /></div>
                        <div className={field}><label className={fieldLabel}>Alignment</label><select value={form.alignment} onChange={set('alignment')}>{ALIGNMENTS.map(a => <option key={a}>{a}</option>)}</select></div>
                    </div>
                    <div className="text-[11px] font-semibold text-gold-dim uppercase tracking-widest border-b border-stone-border pb-1.5">Ability Scores</div>
                    <div className="grid grid-cols-6 gap-2">
                        {(['strength', 'dexterity', 'constitution', 'intelligence', 'wisdom', 'charisma'] as const).map(ab => (
                            <div key={ab} className="flex flex-col gap-1">
                                <label className="text-[10px] font-bold text-ash text-center tracking-wider">{ab.slice(0, 3).toUpperCase()}</label>
                                <input className="text-center" type="number" min={1} max={30} value={form[ab]} onChange={set(ab)} />
                            </div>
                        ))}
                    </div>
                    <div className="text-[11px] font-semibold text-gold-dim uppercase tracking-widest border-b border-stone-border pb-1.5">Combat Stats</div>
                    <div className="grid grid-cols-4 gap-3">
                        <div className={field}><label className={fieldLabel}>Max HP</label><input type="number" min={1} value={form.max_hp} onChange={set('max_hp')} /></div>
                        <div className={field}><label className={fieldLabel}>AC</label><input type="number" min={1} value={form.armor_class} onChange={set('armor_class')} /></div>
                        <div className={field}><label className={fieldLabel}>Speed</label><input type="number" min={0} value={form.speed} onChange={set('speed')} /></div>
                        <div className={field}><label className={fieldLabel}>Hit Die</label><input type="number" min={4} value={form.hit_dice_type} onChange={set('hit_dice_type')} /></div>
                    </div>
                    {error && <p className="text-[13px] text-crimson-light">{error}</p>}
                    <div className="flex justify-end gap-2.5 mt-2">
                        <button type="button" className="bg-stone-mid border-none text-ash-light px-5 py-2.5 rounded-md text-[13px] hover:text-parchment" onClick={onClose}>Cancel</button>
                        <button type="submit" className="bg-crimson border-none text-parchment px-5 py-2.5 rounded-md font-display text-[13px] font-semibold tracking-wide hover:bg-crimson-light">Create Character</button>
                    </div>
                </form>
            </div>
        </div>
    );
}

// web/src/pages/CharacterList.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { listCharacters, createCharacter, deleteCharacter } from '../lib/api';
  import { getUser } from '../lib/auth.svelte';
  import { navigate } from '../lib/router.svelte';
  import Icon from '../lib/Icon.svelte';

  const CLASS_COLORS: Record<string,string> = {
    Barbarian:'#c0392b',Bard:'#8e44ad',Cleric:'#f39c12',Druid:'#27ae60',
    Fighter:'#7f8c8d',Monk:'#16a085',Paladin:'#f1c40f',Ranger:'#2ecc71',
    Rogue:'#2c3e50',Sorcerer:'#e74c3c',Warlock:'#6c3483',Wizard:'#2980b9',
  };
  const RACES    = ['Human','Elf','Dwarf','Halfling','Gnome','Half-Elf','Half-Orc','Tiefling','Dragonborn','Aasimar','Tabaxi','Kenku','Firbolg'];
  const CLASSES  = ['Barbarian','Bard','Cleric','Druid','Fighter','Monk','Paladin','Ranger','Rogue','Sorcerer','Warlock','Wizard','Artificer'];
  const ALIGNMENTS = ['Lawful Good','Neutral Good','Chaotic Good','Lawful Neutral','True Neutral','Chaotic Neutral','Lawful Evil','Neutral Evil','Chaotic Evil'];

  let chars = $state<any[]>([]);
  let loading = $state(true);
  let showCreate = $state(false);
  let createError = $state('');
  let form = $state({
    name:'',race:'Human',class:'Fighter',level:1,background:'',alignment:'True Neutral',
    strength:10,dexterity:10,constitution:10,intelligence:10,wisdom:10,charisma:10,
    max_hp:10,current_hp:10,armor_class:10,speed:30,hit_dice_type:8,hit_dice_remaining:1,
    spellcasting_ability:'none',is_npc:false,
  });

  onMount(async () => {
    try { chars = await listCharacters() || []; } finally { loading = false; }
  });

  async function handleDelete(id: string, e: MouseEvent) {
    e.stopPropagation();
    if (!confirm('Delete this character permanently?')) return;
    await deleteCharacter(id);
    chars = chars.filter(c => c.id !== id);
  }

  async function handleCreate(e: Event) {
    e.preventDefault(); createError = '';
    try {
      const user = getUser();
      const newChar = await createCharacter({
        ...form,
        owner_id: user?.id || '',
        xp:0,temp_hp:0,inspiration:false,attunement_slots:3,
        death_save_successes:0,death_save_failures:0,
        training_armor:[],training_weapons:[],training_tools:[],training_languages:[],
        copper:0,silver:0,electrum:0,gold:0,platinum:0,
        conditions:[],resistances:[],vulnerabilities:[],immunities:[],
        personality_traits:'',ideals:'',bonds:'',flaws:'',notes:'',
        save_prof_strength:false,save_prof_dexterity:false,save_prof_constitution:false,
        save_prof_intelligence:false,save_prof_wisdom:false,save_prof_charisma:false,
        skill_acrobatics:0,skill_animal_handling:0,skill_arcana:0,skill_athletics:0,
        skill_deception:0,skill_history:0,skill_insight:0,skill_intimidation:0,
        skill_investigation:0,skill_medicine:0,skill_nature:0,skill_perception:0,
        skill_performance:0,skill_persuasion:0,skill_religion:0,skill_sleight_of_hand:0,
        skill_stealth:0,skill_survival:0,
      });
      chars = [...chars, newChar];
      showCreate = false;
      navigate(`/characters/${newChar.id}`);
    } catch (err: any) { createError = err?.data?.error || 'Failed to create'; }
  }
</script>

<div class="page">
  <div class="header">
    <div>
      <h1 class="title">Your Characters</h1>
      <p class="subtitle">{chars.length} adventurer{chars.length !== 1 ? 's' : ''} in your party</p>
    </div>
    <button class="create-btn" onclick={() => showCreate = true}>
      <Icon name="plus" size={16}/> New Character
    </button>
  </div>

  {#if loading}
    <div class="loading">Loading characters…</div>
  {:else if chars.length === 0}
    <div class="empty"><Icon name="sword" size={48} class="empty-icon"/><p>No characters yet.</p></div>
  {:else}
    <div class="grid">
      {#each chars as char}
        <div class="card" onclick={() => navigate(`/characters/${char.id}`)}>
          <div class="card-accent" style="background:{CLASS_COLORS[char.class]||'#8b1a1a'}"></div>
          <div class="card-body">
            <div class="card-top">
              <div>
                <h2 class="char-name">{char.name}</h2>
                <p class="char-meta">Level {char.level} {char.race} {char.class}</p>
              </div>
              <button class="delete-btn" onclick={(e) => handleDelete(char.id, e)}>
                <Icon name="trash" size={14}/>
              </button>
            </div>
            <div class="card-stats">
              <span class="stat"><Icon name="shield" size={12}/> {char.armor_class} AC</span>
              <span class="stat">❤ {char.current_hp}/{char.max_hp}</span>
              {#if char.is_npc}<span class="npc-tag">NPC</span>{/if}
            </div>
          </div>
          <Icon name="chevronRight" size={16} class="chevron"/>
        </div>
      {/each}
    </div>
  {/if}
</div>

{#if showCreate}
  <div class="overlay" onclick={() => showCreate = false}>
    <div class="modal" onclick={(e) => e.stopPropagation()}>
      <h2 class="modal-title">Create Character</h2>
      <form onsubmit={handleCreate}>
        <div class="form-row">
          <div class="field"><label>Name *</label><input bind:value={form.name} required placeholder="Character name"/></div>
          <div class="field"><label>Level</label><input type="number" min="1" max="20" bind:value={form.level}/></div>
        </div>
        <div class="form-row">
          <div class="field"><label>Race</label><select bind:value={form.race}>{#each RACES as r}<option>{r}</option>{/each}</select></div>
          <div class="field"><label>Class</label><select bind:value={form.class}>{#each CLASSES as c}<option>{c}</option>{/each}</select></div>
        </div>
        <div class="form-row">
          <div class="field"><label>Background</label><input bind:value={form.background} placeholder="Soldier, Sage…"/></div>
          <div class="field"><label>Alignment</label><select bind:value={form.alignment}>{#each ALIGNMENTS as a}<option>{a}</option>{/each}</select></div>
        </div>
        <div class="section-label">Ability Scores</div>
        <div class="ability-grid">
          {#each ['strength','dexterity','constitution','intelligence','wisdom','charisma'] as ab}
            <div class="ability-field">
              <label>{ab.slice(0,3).toUpperCase()}</label>
              <input type="number" min="1" max="30" bind:value={form[ab as keyof typeof form]}/>
            </div>
          {/each}
        </div>
        <div class="section-label">Combat Stats</div>
        <div class="form-row-4">
          <div class="field"><label>Max HP</label><input type="number" min="1" bind:value={form.max_hp}/></div>
          <div class="field"><label>AC</label><input type="number" min="1" bind:value={form.armor_class}/></div>
          <div class="field"><label>Speed</label><input type="number" min="0" bind:value={form.speed}/></div>
          <div class="field"><label>Hit Die</label><input type="number" min="4" bind:value={form.hit_dice_type}/></div>
        </div>
        {#if createError}<p class="error">{createError}</p>{/if}
        <div class="modal-actions">
          <button type="button" class="cancel-btn" onclick={() => showCreate = false}>Cancel</button>
          <button type="submit" class="submit-btn">Create Character</button>
        </div>
      </form>
    </div>
  </div>
{/if}

<style>
  .page { padding:32px;max-width:1100px;margin:0 auto; }
  .loading,.empty { display:flex;align-items:center;justify-content:center;height:200px;color:var(--ash); }
  .empty { flex-direction:column;gap:12px;padding:80px 20px; }
  :global(.empty-icon) { opacity:.3; }
  .header { display:flex;align-items:flex-start;justify-content:space-between;margin-bottom:32px; }
  .title { font-family:var(--font-display);font-size:28px;font-weight:700;color:var(--parchment); }
  .subtitle { font-size:14px;color:var(--ash);margin-top:4px; }
  .create-btn { display:flex;align-items:center;gap:8px;background:var(--crimson);border:none;color:var(--parchment);padding:10px 18px;border-radius:var(--radius);font-family:var(--font-display);font-size:13px;font-weight:600;letter-spacing:.04em;transition:background var(--transition); }
  .create-btn:hover { background:var(--crimson-light); }
  .grid { display:grid;grid-template-columns:repeat(auto-fill,minmax(320px,1fr));gap:16px; }
  .card { display:flex;align-items:stretch;background:var(--stone);border:1px solid var(--stone-border);border-radius:var(--radius-lg);cursor:pointer;overflow:hidden;transition:border-color var(--transition),transform var(--transition); }
  .card:hover { border-color:var(--gold-dim);transform:translateY(-2px); }
  .card-accent { width:4px;flex-shrink:0; }
  .card-body { flex:1;padding:16px; }
  .card-top { display:flex;align-items:flex-start;justify-content:space-between;margin-bottom:12px; }
  .char-name { font-family:var(--font-display);font-size:17px;font-weight:600;color:var(--parchment); }
  .char-meta { font-size:12px;color:var(--ash);margin-top:3px; }
  .card-stats { display:flex;gap:12px;align-items:center;flex-wrap:wrap; }
  .stat { display:flex;align-items:center;gap:4px;font-size:12px;color:var(--ash-light); }
  .npc-tag { background:rgba(201,168,76,.15);color:var(--gold);border:1px solid rgba(201,168,76,.3);padding:2px 6px;border-radius:3px;font-size:10px;font-weight:600;letter-spacing:.1em; }
  .delete-btn { background:none;border:none;color:var(--stone-border);padding:4px;border-radius:3px;transition:color var(--transition);flex-shrink:0; }
  .delete-btn:hover { color:var(--crimson-light); }
  :global(.chevron) { color:var(--stone-border);align-self:center;margin-right:12px;flex-shrink:0; }
  .overlay { position:fixed;inset:0;background:rgba(0,0,0,.75);z-index:100;display:flex;align-items:center;justify-content:center;padding:20px; }
  .modal { background:var(--stone);border:1px solid var(--stone-border);border-radius:var(--radius-lg);padding:32px;width:100%;max-width:560px;max-height:90vh;overflow-y:auto; }
  .modal-title { font-family:var(--font-display);font-size:22px;font-weight:700;color:var(--parchment);margin-bottom:24px; }
  form { display:flex;flex-direction:column;gap:16px; }
  .form-row { display:grid;grid-template-columns:1fr 1fr;gap:12px; }
  .form-row-4 { display:grid;grid-template-columns:repeat(4,1fr);gap:12px; }
  .field { display:flex;flex-direction:column;gap:6px; }
  .field label { font-size:11px;font-weight:500;color:var(--ash-light);text-transform:uppercase;letter-spacing:.05em; }
  .section-label { font-size:11px;font-weight:600;color:var(--gold-dim);text-transform:uppercase;letter-spacing:.1em;border-bottom:1px solid var(--stone-border);padding-bottom:6px; }
  .ability-grid { display:grid;grid-template-columns:repeat(6,1fr);gap:8px; }
  .ability-field { display:flex;flex-direction:column;gap:4px; }
  .ability-field label { font-size:10px;font-weight:700;color:var(--ash);text-align:center;letter-spacing:.08em; }
  .ability-field input { text-align:center; }
  .error { font-size:13px;color:var(--crimson-light); }
  .modal-actions { display:flex;justify-content:flex-end;gap:10px;margin-top:8px; }
  .cancel-btn { background:var(--stone-mid);border:none;color:var(--ash-light);padding:10px 20px;border-radius:var(--radius);font-size:13px; }
  .cancel-btn:hover { color:var(--parchment); }
  .submit-btn { background:var(--crimson);border:none;color:var(--parchment);padding:10px 20px;border-radius:var(--radius);font-family:var(--font-display);font-size:13px;font-weight:600; }
  .submit-btn:hover { background:var(--crimson-light); }
</style>
