// web/src/pages/Combat.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import * as api from '../lib/api';
  import Icon from '../lib/Icon.svelte';
  import ParticipantRow from '../components/ParticipantRow.svelte';

  let encounters   = $state<any[]>([]);
  let active       = $state<any>(null);
  let participants = $state<any[]>([]);
  let characters   = $state<any[]>([]);
  let selectedId   = $state('');
  let newName      = $state('');
  let loading      = $state(true);
  let showAddPart  = $state(false);
  let partForm     = $state({ character_id:'', name:'', initiative:0, max_hp:10, current_hp:10, armor_class:10, speed:30 });

  async function reload() {
    const [enc, chars] = await Promise.all([api.listEncounters(), api.listCharacters()]);
    encounters = enc || []; characters = chars || [];
    try {
      const act = await api.getActiveEncounter();
      active = act;
      if (act) {
        const parts = await api.listParticipants(act.id);
        participants = (parts || []).sort((a:any,b:any) => b.initiative - a.initiative);
      }
    } catch { active = null; participants = []; }
  }

  onMount(() => reload().finally(() => loading = false));

  async function loadEnc(id: string) {
    selectedId = id;
    const parts = await api.listParticipants(id);
    participants = (parts || []).sort((a:any,b:any) => b.initiative - a.initiative);
  }

  async function createEnc() {
    if (!newName.trim()) return;
    await api.createEncounter(newName.trim());
    newName = ''; await reload();
  }

  async function addPart(e: Event) {
    e.preventDefault();
    const encId = active?.id || selectedId; if (!encId) return;
    await api.addParticipant(encId, {
      character_id: partForm.character_id,
      initiative:   partForm.initiative,
    });
    showAddPart = false;
    partForm = { character_id:'', name:'', initiative:0, max_hp:10, current_hp:10, armor_class:10, speed:30 };
    await reload();
  }

  function selectChar(charId: string) {
    const c = characters.find((ch:any) => ch.id === charId);
    if (c) partForm = { ...partForm, character_id:charId, name:c.name, max_hp:c.max_hp, current_hp:c.current_hp, armor_class:c.armor_class, speed:c.speed };
    else   partForm = { ...partForm, character_id:charId };
  }

  let encId      = $derived(active?.id || selectedId);
  let currentEnc = $derived(active || encounters.find((e:any) => e.id === selectedId));
</script>

{#if loading}
  <div class="loading">Loading…</div>
{:else}
<div class="page">

  <!-- Sidebar -->
  <div class="sidebar">
    <h2 class="side-title">Encounters</h2>
    <div class="new-enc">
      <input bind:value={newName} placeholder="Encounter name…"
        onkeydown={(e) => e.key==='Enter' && createEnc()}/>
      <button class="create-btn" onclick={createEnc}><Icon name="plus" size={14}/></button>
    </div>
    <div class="enc-list">
      {#each encounters as enc}
        <div class="enc-item"
          class:active={enc.id===encId}
          class:live={enc.is_active}
          onclick={() => loadEnc(enc.id)}>
          <div>
            <div class="enc-name">{enc.name}</div>
            <div class="enc-meta">{enc.is_active ? `Round ${enc.round} · LIVE` : 'Inactive'}</div>
          </div>
          {#if enc.is_active}<div class="live-dot"></div>{/if}
        </div>
      {/each}
      {#if encounters.length === 0}
        <div class="empty-enc">No encounters yet.</div>
      {/if}
    </div>
  </div>

  <!-- Main -->
  <div class="main">
    {#if currentEnc}
      <div class="enc-header">
        <div>
          <h1 class="enc-title">{currentEnc.name}</h1>
          {#if currentEnc.is_active}
            <span class="round-badge">Round {currentEnc.round}</span>
          {/if}
        </div>
        <div class="enc-actions">
          {#if !currentEnc.is_active}
            <button class="action-btn" onclick={() => api.startEncounter(currentEnc.id).then(reload)}>
              <Icon name="play" size={15}/> Start
            </button>
          {:else}
            <button class="action-btn" onclick={() => api.nextRound(currentEnc.id).then(reload)}>
              <Icon name="skip" size={15}/> Next Round
            </button>
            <button class="action-btn danger" onclick={() => api.endEncounter(currentEnc.id).then(reload)}>
              <Icon name="stop" size={15}/> End
            </button>
          {/if}
          <button class="action-btn" onclick={() => showAddPart = !showAddPart}>
            <Icon name="plus" size={15}/> Add Combatant
          </button>
        </div>
      </div>

      {#if showAddPart}
        <form class="add-form" onsubmit={addPart}>
          <div class="form-row">
            <div class="field">
              <label>Character</label>
              <select value={partForm.character_id}
                onchange={(e) => selectChar((e.target as HTMLSelectElement).value)}>
                <option value="">— Select a character —</option>
                {#each characters as c}
                  <option value={c.id}>{c.name}</option>
                {/each}
              </select>
            </div>
            <div class="field">
              <label>Initiative</label>
              <input type="number" bind:value={partForm.initiative}/>
            </div>
          </div>
          <div class="modal-actions">
            <button type="button" class="cancel-btn" onclick={() => showAddPart=false}>Cancel</button>
            <button type="submit" class="submit-btn" disabled={!partForm.character_id}>Add to Battle</button>
          </div>
        </form>
      {/if}

      <div class="tracker">
        {#if participants.length === 0}
          <div class="empty-tracker">
            <Icon name="sword" size={40} class="empty-icon"/>
            <p>No combatants yet.</p>
          </div>
        {/if}
        {#each participants as p}
          <ParticipantRow
            {p} {encId}
            onDmg={(n) => api.participantDamage(encId, p.id, n).then(reload)}
            onHeal={(n) => api.participantHeal(encId, p.id, n).then(reload)}
            onRemove={() => api.removeParticipant(encId, p.id).then(reload)}
          />
        {/each}
      </div>

    {:else}
      <div class="no-enc">
        <Icon name="sword" size={64} class="no-enc-icon"/>
        <p>Select or create an encounter to begin</p>
      </div>
    {/if}
  </div>

</div>
{/if}

<style>
.loading { display:flex;align-items:center;justify-content:center;height:200px;color:var(--ash); }
.page { display:flex;height:100vh;overflow:hidden; }
.sidebar { width:260px;flex-shrink:0;background:var(--stone);border-right:1px solid var(--stone-border);display:flex;flex-direction:column;padding:20px;gap:12px;overflow-y:auto; }
.side-title { font-family:var(--font-display);font-size:15px;font-weight:700;color:var(--parchment); }
.new-enc { display:flex;gap:6px; }
.new-enc input { flex:1; }
.create-btn { background:var(--crimson);border:none;color:var(--parchment);padding:8px 10px;border-radius:var(--radius-sm); }
.create-btn:hover { background:var(--crimson-light); }
.enc-list { display:flex;flex-direction:column;gap:4px;flex:1; }
.enc-item { padding:10px 12px;border-radius:var(--radius);border:1px solid transparent;cursor:pointer;transition:all var(--transition);display:flex;align-items:center;justify-content:space-between; }
.enc-item:hover { background:var(--stone-mid); }
.enc-item.active { background:var(--stone-mid);border-color:var(--stone-border); }
.enc-item.live { border-color:var(--crimson); }
.enc-name { font-size:13px;font-weight:500;color:var(--parchment); }
.enc-meta { font-size:11px;color:var(--ash);margin-top:2px; }
.live-dot { width:8px;height:8px;border-radius:50%;background:var(--crimson-light);box-shadow:0 0 6px var(--crimson-glow); }
.empty-enc { font-size:13px;color:var(--ash);text-align:center;padding:20px 0; }
.main { flex:1;overflow-y:auto;padding:24px 32px; }
.enc-header { display:flex;align-items:center;justify-content:space-between;margin-bottom:20px;flex-wrap:wrap;gap:12px; }
.enc-title { font-family:var(--font-display);font-size:24px;font-weight:700;color:var(--parchment); }
.round-badge { font-size:12px;background:rgba(139,26,26,.2);color:var(--crimson-light);border:1px solid rgba(139,26,26,.3);padding:3px 10px;border-radius:12px;margin-top:4px;display:inline-block; }
.enc-actions { display:flex;gap:8px;flex-wrap:wrap; }
.action-btn { display:flex;align-items:center;gap:6px;background:var(--stone);border:1px solid var(--stone-border);color:var(--ash-light);padding:8px 14px;border-radius:var(--radius);font-size:13px;transition:all var(--transition); }
.action-btn:hover { border-color:var(--gold-dim);color:var(--parchment); }
.action-btn.danger { background:rgba(139,26,26,.15);border-color:rgba(139,26,26,.3);color:var(--crimson-light); }
.action-btn.danger:hover { background:rgba(139,26,26,.25); }
.add-form { background:var(--stone);border:1px solid var(--stone-border);border-radius:var(--radius-lg);padding:20px;margin-bottom:20px;display:flex;flex-direction:column;gap:12px; }
.form-row { display:flex;gap:12px;flex-wrap:wrap; }
.form-row > * { flex:1;min-width:120px; }
.field { display:flex;flex-direction:column;gap:5px; }
.field label { font-size:11px;color:var(--ash);text-transform:uppercase;letter-spacing:.05em; }
.modal-actions { display:flex;justify-content:flex-end;gap:8px; }
.cancel-btn { background:var(--stone-mid);border:none;color:var(--ash-light);padding:8px 16px;border-radius:var(--radius);font-size:13px; }
.submit-btn { background:var(--crimson);border:none;color:var(--parchment);padding:8px 16px;border-radius:var(--radius);font-family:var(--font-display);font-size:13px;font-weight:600; }
.submit-btn:disabled { opacity:.4;cursor:not-allowed; }
.tracker { display:flex;flex-direction:column;gap:6px; }
.empty-tracker { text-align:center;padding:60px 20px;color:var(--ash); }
:global(.empty-icon) { margin:0 auto 12px;display:block;opacity:.3; }
.no-enc { display:flex;flex-direction:column;align-items:center;justify-content:center;height:60vh;color:var(--ash);gap:12px; }
:global(.no-enc-icon) { opacity:.2; }
</style>

// web/src/pages/Combat.tsx
import { useState, useEffect } from 'react';
import * as api from '../lib/api';
import { IconPlus, IconSword, IconSkip, IconStop, IconPlay, IconTrash, IconChevronDown, IconChevronUp } from '../components/Icon';

const field = "flex flex-col gap-1.5";
const fieldLabel = "text-[11px] text-ash uppercase tracking-wide";

export function Combat() {
    const [encounters, setEncounters] = useState<any[]>([]);
    const [active, setActive] = useState<any>(null);
    const [participants, setParticipants] = useState<any[]>([]);
    const [characters, setCharacters] = useState<any[]>([]);
    const [selectedId, setSelectedId] = useState('');
    const [newName, setNewName] = useState('');
    const [loading, setLoading] = useState(true);
    const [showAddPart, setShowAddPart] = useState(false);
    const [partForm, setPartForm] = useState({ character_id: '', name: '', initiative: 0, max_hp: 10, current_hp: 10, armor_class: 10, speed: 30 });

    const reload = async () => {
        const [enc, chars] = await Promise.all([api.listEncounters(), api.listCharacters()]);
        setEncounters(enc || []); setCharacters(chars || []);
        try {
            const act = await api.getActiveEncounter();
            setActive(act);
            if (act) {
                const parts = await api.listParticipants(act.id);
                setParticipants((parts || []).sort((a: any, b: any) => b.initiative - a.initiative));
            }
        } catch { setActive(null); setParticipants([]); }
    };

    useEffect(() => { reload().finally(() => setLoading(false)); }, []);

    const loadEnc = async (id: string) => {
        setSelectedId(id);
        const parts = await api.listParticipants(id);
        setParticipants((parts || []).sort((a: any, b: any) => b.initiative - a.initiative));
    };

    const createEnc = () => {
        if (!newName.trim()) return;
        api.createEncounter(newName.trim()).then(() => { setNewName(''); reload(); });
    };

    const addPart = async (e: React.FormEvent) => {
        e.preventDefault();
        const encId = active?.id || selectedId;
        if (!encId) return;
        await api.addParticipant(encId, partForm);
        setShowAddPart(false);
        setPartForm({ character_id: '', name: '', initiative: 0, max_hp: 10, current_hp: 10, armor_class: 10, speed: 30 });
        reload();
    };

    const selectChar = (charId: string) => {
        const c = characters.find((ch: any) => ch.id === charId);
        if (c) setPartForm(f => ({ ...f, character_id: charId, name: c.name, max_hp: c.max_hp, current_hp: c.current_hp, armor_class: c.armor_class, speed: c.speed }));
        else setPartForm(f => ({ ...f, character_id: charId }));
    };

    const encId = active?.id || selectedId;
    const currentEnc = active || encounters.find((e: any) => e.id === selectedId);

    if (loading) return <div className="flex items-center justify-center h-[200px] text-ash">Loading…</div>;

    return (
        <div className="flex h-screen overflow-hidden">
            <div className="w-[260px] shrink-0 bg-stone border-r border-stone-border flex flex-col p-5 gap-3 overflow-y-auto">
                <h2 className="font-display text-[15px] font-bold text-parchment">Encounters</h2>
                <div className="flex gap-1.5">
                    <input className="flex-1" value={newName} onChange={e => setNewName(e.target.value)}
                        placeholder="Encounter name…" onKeyDown={e => e.key === 'Enter' && createEnc()} />
                    <button className="bg-crimson border-none text-parchment px-2.5 py-2 rounded-sm hover:bg-crimson-light" onClick={createEnc}><IconPlus size={14} /></button>
                </div>
                <div className="flex flex-col gap-1 flex-1">
                    {encounters.map((enc: any) => (
                        <div key={enc.id}
                            className={`px-3 py-2.5 rounded-md border cursor-pointer transition-all duration-180 flex items-center justify-between hover:bg-stone-mid ${enc.id === encId ? 'bg-stone-mid border-stone-border' : 'border-transparent'} ${enc.is_active ? 'border-crimson' : ''}`}
                            onClick={() => loadEnc(enc.id)}>
                            <div>
                                <div className="text-[13px] font-medium text-parchment">{enc.name}</div>
                                <div className="text-[11px] text-ash mt-0.5">{enc.is_active ? `Round ${enc.round} · LIVE` : 'Inactive'}</div>
                            </div>
                            {enc.is_active && <div className="w-2 h-2 rounded-full bg-crimson-light shadow-[0_0_6px_#c0392b]" />}
                        </div>
                    ))}
                    {encounters.length === 0 && <div className="text-[13px] text-ash text-center py-5">No encounters yet.</div>}
                </div>
            </div>

            <div className="flex-1 overflow-y-auto py-6 px-8">
                {currentEnc ? (
                    <>
                        <div className="flex items-center justify-between mb-5 flex-wrap gap-3">
                            <div>
                                <h1 className="font-display text-2xl font-bold text-parchment">{currentEnc.name}</h1>
                                {currentEnc.is_active && <span className="text-xs bg-crimson/20 text-crimson-light border border-crimson/30 px-2.5 py-0.5 rounded-full mt-1 inline-block">Round {currentEnc.round}</span>}
                            </div>
                            <div className="flex gap-2 flex-wrap">
                                {!currentEnc.is_active
                                    ? <button className="flex items-center gap-1.5 bg-stone border border-stone-border text-ash-light px-3.5 py-2 rounded-md text-[13px] transition-all duration-180 hover:border-gold-dim hover:text-parchment" onClick={() => api.startEncounter(currentEnc.id).then(reload)}><IconPlay size={15} /> Start</button>
                                    : <>
                                        <button className="flex items-center gap-1.5 bg-stone border border-stone-border text-ash-light px-3.5 py-2 rounded-md text-[13px] transition-all duration-180 hover:border-gold-dim hover:text-parchment" onClick={() => api.nextRound(currentEnc.id).then(reload)}><IconSkip size={15} /> Next Round</button>
                                        <button className="flex items-center gap-1.5 bg-crimson/15 border border-crimson/30 text-crimson-light px-3.5 py-2 rounded-md text-[13px] hover:bg-crimson/25" onClick={() => api.endEncounter(currentEnc.id).then(reload)}><IconStop size={15} /> End</button>
                                    </>
                                }
                                <button className="flex items-center gap-1.5 bg-stone border border-stone-border text-ash-light px-3.5 py-2 rounded-md text-[13px] transition-all duration-180 hover:border-gold-dim hover:text-parchment" onClick={() => setShowAddPart(v => !v)}><IconPlus size={15} /> Add Combatant</button>
                            </div>
                        </div>

                        {showAddPart && (
                            <form onSubmit={addPart} className="bg-stone border border-stone-border rounded-lg p-5 mb-5 flex flex-col gap-3">
                                <div className="flex gap-3 flex-wrap [&>*]:flex-1 [&>*]:min-w-[120px]">
                                    <div className={field}>
                                        <label className={fieldLabel}>From Characters</label>
                                        <select value={partForm.character_id} onChange={e => selectChar(e.target.value)}>
                                            <option value="">— Custom NPC —</option>
                                            {characters.map((c: any) => <option key={c.id} value={c.id}>{c.name}</option>)}
                                        </select>
                                    </div>
                                    <div className={field}><label className={fieldLabel}>Name *</label><input value={partForm.name} onChange={e => setPartForm(f => ({ ...f, name: e.target.value }))} required /></div>
                                    <div className={field}><label className={fieldLabel}>Initiative</label><input type="number" value={partForm.initiative} onChange={e => setPartForm(f => ({ ...f, initiative: +e.target.value }))} /></div>
                                    <div className={field}><label className={fieldLabel}>Max HP</label><input type="number" min={1} value={partForm.max_hp} onChange={e => setPartForm(f => ({ ...f, max_hp: +e.target.value, current_hp: +e.target.value }))} /></div>
                                    <div className={field}><label className={fieldLabel}>AC</label><input type="number" min={1} value={partForm.armor_class} onChange={e => setPartForm(f => ({ ...f, armor_class: +e.target.value }))} /></div>
                                </div>
                                <div className="flex justify-end gap-2">
                                    <button type="button" className="bg-stone-mid border-none text-ash-light px-4 py-2 rounded-md text-[13px]" onClick={() => setShowAddPart(false)}>Cancel</button>
                                    <button type="submit" className="bg-crimson border-none text-parchment px-4 py-2 rounded-md font-display text-[13px] font-semibold">Add to Battle</button>
                                </div>
                            </form>
                        )}

                        <div className="flex flex-col gap-1.5">
                            {participants.length === 0 && (
                                <div className="text-center py-[60px] px-5 text-ash"><IconSword size={40} className="mx-auto mb-3 block opacity-30" /><p>No combatants yet.</p></div>
                            )}
                            {participants.map((p: any) => (
                                <ParticipantRow key={p.id} p={p} encId={encId}
                                    onDmg={n => api.participantDamage(encId, p.id, n).then(reload)}
                                    onHeal={n => api.participantHeal(encId, p.id, n).then(reload)}
                                    onRemove={() => api.removeParticipant(encId, p.id).then(reload)}
                                />
                            ))}
                        </div>
                    </>
                ) : (
                    <div className="flex flex-col items-center justify-center h-[60vh] text-ash gap-3">
                        <IconSword size={64} className="opacity-20" />
                        <p>Select or create an encounter to begin</p>
                    </div>
                )}
            </div>
        </div>
    );
}

function ParticipantRow({ p, onDmg, onHeal, onRemove }: {
    p: any; encId: string;
    onDmg: (n: number) => void;
    onHeal: (n: number) => void;
    onRemove: () => void;
}) {
    const [expanded, setExpanded] = useState(false);
    const [amount, setAmount] = useState('');
    const hpPct = Math.max(0, Math.min(100, (p.current_hp / p.max_hp) * 100));
    const hpColor = hpPct > 50 ? '#27ae60' : hpPct > 25 ? '#f39c12' : '#c0392b';

    return (
        <div className={`flex items-stretch bg-stone border border-stone-border rounded-lg overflow-hidden ${!p.is_active ? 'opacity-40' : ''}`}>
            <div className="w-12 shrink-0 bg-stone-mid flex items-center justify-center font-display text-lg font-bold text-gold">{p.initiative}</div>
            <div className="flex-1">
                <div className="flex items-center gap-3 px-4 py-3 cursor-pointer hover:bg-white/[0.02]" onClick={() => setExpanded(v => !v)}>
                    <div>
                        <div className="text-[15px] font-medium text-parchment flex-1">{p.name}</div>
                        {p.conditions?.length > 0 && (
                            <div className="flex gap-1 flex-wrap mt-0.5">
                                {p.conditions.map((c: string) => <span key={c} className="text-[10px] bg-crimson/20 text-crimson-light rounded-sm px-1.5 py-0.5">{c}</span>)}
                            </div>
                        )}
                    </div>
                    <div className="flex items-center gap-1.5 flex-1">
                        <div className="w-20 h-1.5 bg-stone-border rounded-sm overflow-hidden">
                            <div style={{ width: `${hpPct}%`, background: hpColor, height: '100%', borderRadius: 3 }} />
                        </div>
                        <span className="font-bold text-base" style={{ color: hpColor }}>{p.current_hp}</span>
                        <span className="text-xs text-ash">/{p.max_hp}</span>
                    </div>
                    <div className="flex gap-2.5 text-xs text-ash">
                        <span>AC {p.armor_class}</span>
                        {p.concentration && <span className="text-[#9b59b6]">⊛</span>}
                    </div>
                    {expanded ? <IconChevronUp size={14} className="text-ash shrink-0" /> : <IconChevronDown size={14} className="text-ash shrink-0" />}
                </div>
                {expanded && (
                    <div className="px-4 py-3 border-t border-stone-border flex items-center gap-2.5 bg-stone-mid">
                        <input className="w-20 text-center px-2 py-1.5" type="number" min={1} value={amount}
                            onChange={e => setAmount(e.target.value)} placeholder="Amount" />
                        <button className="bg-crimson/20 border border-crimson/30 text-crimson-light px-3 py-1.5 rounded-sm text-xs hover:bg-crimson/35" onClick={() => { if (amount) { onDmg(+amount); setAmount(''); } }}>⚔ Damage</button>
                        <button className="bg-emerald/15 border border-emerald/30 text-[#27ae60] px-3 py-1.5 rounded-sm text-xs hover:bg-emerald/25" onClick={() => { if (amount) { onHeal(+amount); setAmount(''); } }}>❤ Heal</button>
                        <button className="flex items-center gap-1 bg-transparent border-none text-ash text-xs ml-auto hover:text-crimson-light" onClick={onRemove}><IconTrash size={13} /></button>
                    </div>
                )}
            </div>
        </div>
    );
}
