// web/src/pages/Login.svelte
<script lang="ts">
  import { login as apiLogin, register as apiRegister } from '../lib/api';
  import { authLogin } from '../lib/auth.svelte';
  import { navigate } from '../lib/router.svelte';
  import Icon from '../lib/Icon.svelte';

  let mode    = $state<'login'|'register'>('login');
  let form    = $state({ username:'', email:'', password:'', registration_code:'' });
  let error   = $state('');
  let loading = $state(false);

  async function submit(e: Event) {
    e.preventDefault(); error = ''; loading = true;
    try {
      const res = mode === 'login'
        ? await apiLogin(form.email, form.password)
        : await apiRegister(form.username, form.email, form.password, form.registration_code);
      await authLogin(res.token);
      navigate('/characters');
    } catch (err: any) {
      error = err?.data?.error || 'Something went wrong';
    } finally { loading = false; }
  }
</script>

<div class="page">
  <div class="card">
    <div class="header">
      <Icon name="skull" size={40} class="icon" />
      <h1 class="title">Behold</h1>
      <p class="subtitle">Your digital grimoire</p>
    </div>
    <div class="tabs">
      <button class="tab" class:active={mode==='login'} onclick={() => mode='login'}>Sign In</button>
      <button class="tab" class:active={mode==='register'} onclick={() => mode='register'}>Register</button>
    </div>
    <form onsubmit={submit}>
      {#if mode === 'register'}
        <div class="field"><label>Username</label><input bind:value={form.username} required placeholder="Your adventurer name"/></div>
      {/if}
      <div class="field"><label>Email</label><input type="email" bind:value={form.email} required placeholder="your@email.com"/></div>
      <div class="field"><label>Password</label><input type="password" bind:value={form.password} required placeholder="••••••••"/></div>
      {#if mode === 'register'}
        <div class="field"><label>Registration Code</label><input bind:value={form.registration_code} required placeholder="Provided by your DM"/></div>
      {/if}
      {#if error}<p class="error">{error}</p>{/if}
      <button class="submit" type="submit" disabled={loading}>
        {loading ? 'Loading…' : mode === 'login' ? 'Enter the Realm' : 'Join the Party'}
      </button>
    </form>
  </div>
</div>

<style>
  .page { min-height:100vh;display:flex;align-items:center;justify-content:center;background:var(--ink);background-image:radial-gradient(ellipse at 20% 50%,rgba(139,26,26,.08) 0%,transparent 60%),radial-gradient(ellipse at 80% 20%,rgba(201,168,76,.05) 0%,transparent 50%);padding:20px; }
  .card { width:100%;max-width:400px;background:var(--stone);border:1px solid var(--stone-border);border-radius:var(--radius-lg);padding:40px;box-shadow:0 24px 64px rgba(0,0,0,.6); }
  .header { text-align:center;margin-bottom:28px; }
  :global(.icon) { color:var(--crimson-light);margin-bottom:12px; }
  .title { font-family:var(--font-display);font-size:32px;font-weight:900;color:var(--parchment);letter-spacing:.1em; }
  .subtitle { font-family:var(--font-body);font-size:15px;color:var(--ash);margin-top:4px; }
  .tabs { display:flex;gap:4px;background:var(--stone-mid);border-radius:var(--radius);padding:4px;margin-bottom:24px; }
  .tab { flex:1;background:none;border:none;color:var(--ash);padding:8px;border-radius:var(--radius-sm);font-size:13px;font-weight:500;transition:all var(--transition); }
  .tab.active { background:var(--stone-light);color:var(--parchment); }
  form { display:flex;flex-direction:column;gap:16px; }
  .field { display:flex;flex-direction:column;gap:6px; }
  .field label { font-size:12px;font-weight:500;color:var(--ash-light);text-transform:uppercase;letter-spacing:.05em; }
  .error { font-size:13px;color:var(--crimson-light);background:rgba(139,26,26,.15);border:1px solid rgba(139,26,26,.3);border-radius:var(--radius-sm);padding:8px 12px; }
  .submit { background:var(--crimson);border:none;color:var(--parchment);padding:12px;border-radius:var(--radius);font-family:var(--font-display);font-size:14px;font-weight:600;letter-spacing:.05em;transition:background var(--transition);margin-top:4px; }
  .submit:hover:not(:disabled) { background:var(--crimson-light); }
  .submit:disabled { opacity:.5;cursor:not-allowed; }
</style>

// web/src/pages/Login.tsx
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { login as apiLogin, register as apiRegister } from '../lib/api';
import { useAuth } from '../context/AuthContext';
import { IconSkull } from '../components/Icon';

export function Login() {
    const [mode, setMode] = useState<'login' | 'register'>('login');
    const [form, setForm] = useState({
        username: '',
        email: '',
        password: '',
        registration_code: '',
        role: '',
    });
    const [error, setError] = useState('');
    const [loading, setLoading] = useState(false);
    const { login } = useAuth();
    const navigate = useNavigate();

    const set = (k: string) => (e: React.ChangeEvent<HTMLInputElement>) =>
        setForm(f => ({ ...f, [k]: e.target.value }));

    const submit = async (e: React.FormEvent) => {
        e.preventDefault();
        setError(''); setLoading(true);
        try {
            const res = mode === 'login'
                ? await apiLogin(form.username, form.password)
                : await apiRegister(form.username, form.email, form.password, form.registration_code, form.role);
            login(res.token);
            navigate('/characters');
        } catch (err: any) {
            setError(err?.data?.error || 'Something went wrong');
        } finally { setLoading(false); }
    };

    return (
        <div
            className="min-h-screen flex items-center justify-center bg-ink p-5"
            style={{
                backgroundImage:
                    'radial-gradient(ellipse at 20% 50%, rgba(139,26,26,0.08) 0%, transparent 60%), radial-gradient(ellipse at 80% 20%, rgba(201,168,76,0.05) 0%, transparent 50%)',
            }}
        >
            <div className="w-full max-w-[400px] bg-stone border border-stone-border rounded-lg p-10 shadow-[0_24px_64px_rgba(0,0,0,0.6)]">
                <div className="text-center mb-7">
                    <IconSkull size={40} className="text-crimson-light mx-auto mb-3" />
                    <h1 className="font-display text-[32px] font-black text-parchment tracking-[0.1em]">Behold</h1>
                    <p className="font-body text-[15px] text-ash mt-1">Your digital grimoire</p>
                </div>
                <div className="flex gap-1 bg-stone-mid rounded-md p-1 mb-6">
                    <button className={`flex-1 bg-transparent border-none py-2 rounded-sm text-[13px] font-medium transition-all duration-180 ${mode === 'login' ? 'bg-stone-light text-parchment' : 'text-ash'}`} onClick={() => setMode('login')}>Sign In</button>
                    <button className={`flex-1 bg-transparent border-none py-2 rounded-sm text-[13px] font-medium transition-all duration-180 ${mode === 'register' ? 'bg-stone-light text-parchment' : 'text-ash'}`} onClick={() => setMode('register')}>Register</button>
                </div>
                <form onSubmit={submit} className="flex flex-col gap-4">
                    <div className="flex flex-col gap-1.5">
                        <label className="text-xs font-medium text-ash-light uppercase tracking-wide">Username</label>
                        <input value={form.username} onChange={set('username')} required placeholder="Your adventurer name" />
                    </div>
                    {mode === 'register' && (
                        <div className="flex flex-col gap-1.5">
                            <label className="text-xs font-medium text-ash-light uppercase tracking-wide">Email</label>
                            <input type="email" value={form.email} onChange={set('email')} required placeholder="your@email.com" />
                        </div>
                    )}
                    <div className="flex flex-col gap-1.5">
                        <label className="text-xs font-medium text-ash-light uppercase tracking-wide">Password</label>
                        <input type="password" value={form.password} onChange={set('password')} required placeholder="••••••••" />
                    </div>
                    {mode === 'register' && (
                        <div className="flex flex-col gap-1.5">
                            <label className="text-xs font-medium text-ash-light uppercase tracking-wide">Registration Code</label>
                            <input value={form.registration_code} onChange={set('registration_code')} required placeholder="Provided by your DM" />
                        </div>
                    )}
                    {mode === 'register' && (
                        <div className="flex flex-col gap-1.5">
                            <label className="text-xs font-medium text-ash-light uppercase tracking-wide">Role</label>
                            <input value={form.role} onChange={set('role')} required placeholder="player/dm" />
                        </div>
                    )}
                    {error && <p className="text-[13px] text-crimson-light bg-crimson/15 border border-crimson/30 rounded-sm px-3 py-2">{error}</p>}
                    <button
                        className="bg-crimson border-none text-parchment py-3 rounded-md font-display text-sm font-semibold tracking-wide transition-colors duration-180 mt-1 hover:enabled:bg-crimson-light disabled:opacity-50 disabled:cursor-not-allowed"
                        type="submit" disabled={loading}>
                        {loading ? 'Loading…' : mode === 'login' ? 'Enter the Realm' : 'Join the Party'}
                    </button>
                </form>
            </div>
        </div>
    );
}
